package com.ly.justsoso.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ly.justsoso.enjoypictures.bean.PictureData;

import com.ly.justsoso.greendao.PictureDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pictureDataDaoConfig;

    private final PictureDataDao pictureDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pictureDataDaoConfig = daoConfigMap.get(PictureDataDao.class).clone();
        pictureDataDaoConfig.initIdentityScope(type);

        pictureDataDao = new PictureDataDao(pictureDataDaoConfig, this);

        registerDao(PictureData.class, pictureDataDao);
    }
    
    public void clear() {
        pictureDataDaoConfig.getIdentityScope().clear();
    }

    public PictureDataDao getPictureDataDao() {
        return pictureDataDao;
    }

}
