package com.ly.justsoso.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ly.justsoso.enjoypictures.bean.PictureData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PICTURE_DATA".
*/
public class PictureDataDao extends AbstractDao<PictureData, Long> {

    public static final String TABLENAME = "PICTURE_DATA";

    /**
     * Properties of entity PictureData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ThumbURL = new Property(1, String.class, "thumbURL", false, "THUMB_URL");
        public final static Property ObjURL = new Property(2, String.class, "objURL", false, "OBJ_URL");
    };


    public PictureDataDao(DaoConfig config) {
        super(config);
    }
    
    public PictureDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PICTURE_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"THUMB_URL\" TEXT," + // 1: thumbURL
                "\"OBJ_URL\" TEXT);"); // 2: objURL
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PICTURE_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PictureData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String thumbURL = entity.getThumbURL();
        if (thumbURL != null) {
            stmt.bindString(2, thumbURL);
        }
 
        String objURL = entity.getObjURL();
        if (objURL != null) {
            stmt.bindString(3, objURL);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PictureData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String thumbURL = entity.getThumbURL();
        if (thumbURL != null) {
            stmt.bindString(2, thumbURL);
        }
 
        String objURL = entity.getObjURL();
        if (objURL != null) {
            stmt.bindString(3, objURL);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PictureData readEntity(Cursor cursor, int offset) {
        PictureData entity = new PictureData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // thumbURL
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // objURL
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PictureData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThumbURL(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setObjURL(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PictureData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PictureData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
